web/myhome/urls.py
from django.conf.urls import url
from . views import IndexViews,LoginViews,CartViews,PersonalViews,OrderViews,CenterViews


urlpatterns = [
    # 首页
    url(r'^$',IndexViews.myhome_index,name="myhome_index"),
    # 列表
    url(r'^list/(?P<cid>[0-9]+)',IndexViews.myhome_list,name="myhome_list"),
    url(r'^all_list/',IndexViews.myhome_all_list,name="myhome_all_list"),

    # # 详情
    url(r'^info/',IndexViews.myhome_info,name="myhome_info"),

    # 登录
    url(r'^login/',LoginViews.myhome_login,name="myhome_login"),
    url(r'^dologin/',LoginViews.myhome_dologin,name="myhome_dologin"),
    url(r'^isphone/',LoginViews.isphone,name="isphone"),
    # 退出登录
    url(r'^logout/',LoginViews.myhome_logout,name="myhome_logout"),
    # 第三方登录
    url(r'github_login', LoginViews.git_login, name='github_login'),
    url(r'github_check', LoginViews.git_check, name='github_check'),

    # 注册
    url(r'^register/',LoginViews.myhome_register,name="myhome_register"),
    url(r'^doregister/',LoginViews.myhome_doregister,name="myhome_doregister"),

    # 短信发送
    url(r'^sendMsg/',LoginViews.myhome_sendMsg,name="myhome_sendMsg"),

    # 个人中心首页
    url(r'^personal/$', PersonalViews.myhome_personal, name="myhome_personal"),
    # 个人信息页面
    url(r'^information/$',PersonalViews.myhome_information,name="myhome_information"),
    # 执行个人信息修改
    url(r'^doinfor/$',PersonalViews.myhome_doinfor,name="myhome_doinfor"),


    # 安全设置
    url(r'^safety/$',PersonalViews.myhome_safety,name="myhome_safety"),
    # 密码修改页面
    url(r'^password/$',PersonalViews.myhome_password,name="myhome_password"),
    # 执行密码修改
    url(r'^passwordmol/$',PersonalViews.myhome_passwordmol,name="myhome_passwordmol"),
    # 换绑手机号页面
    url(r'^phone/$',PersonalViews.myhome_phone,name="myhome_phone"),
    # 执行更换手机号
    url(r'^phone/change/$',PersonalViews.myhome_phone_change,name="myhome_phone_change"),
    # 绑定邮箱页面
    url(r'^email/$',PersonalViews.myhome_email,name="myhome_email"),
    # 执行绑定邮箱
    url(r'^email/bind/$',PersonalViews.myhome_email_bind,name="myhome_email_bind"),


    # 我的收藏
    url(r'^collect/$', PersonalViews.myhome_collect, name="myhome_collect"),
    # 删除收藏商品操作
    url(r'^collect/del/$',PersonalViews.myhome_collect_del,name="myhome_collect_del"),


    # 地址管理页面
    url(r'^address/$', PersonalViews.myhome_address, name="myhome_address"),
    # 设置为默认地址
    url(r'^address/def/$', PersonalViews.myhome_address_def, name="myhome_address_def"),
    # 添加地址
    url(r'^address/add/$', PersonalViews.myhome_address_add, name="myhome_address_add"),
    # 执行添加地址
    url(r'^address/doadd/$', PersonalViews.myhome_address_doadd, name="myhome_address_doadd"),
    # 地址编辑页面
    url(r'^address/edit/$', PersonalViews.myhome_address_edit, name="myhome_address_edit"),
    # 执行编辑
    url(r'^address/doedit/$', PersonalViews.myhome_address_doedit, name="myhome_address_doedit"),
    # 地址删除
    url(r'^address/del/$', PersonalViews.myhome_address_del, name="myhome_address_del"),

    # 发送html邮箱
    url(r'^email/html/$',PersonalViews.myhome_email_html,name="myhome_email_html"),

    


    # 购物车  增删改查 
    url(r'^cart/index/',CartViews.myhome_cart_index,name="myhome_cart_index"),
    # 添加
    url(r'^cart/add/',CartViews.myhome_cart_add,name="myhome_cart_add"),
    # 删除
    url(r'^cart/del/',CartViews.myhome_cart_del,name="myhome_cart_del"),
    # 清空
    url(r'^cart/clear/',CartViews.myhome_cart_clear,name="myhome_cart_clear"),
    # 编辑
    url(r'^cart/edit/',CartViews.myhome_cart_edit,name="myhome_cart_edit"),
    
    # 订单管理
    url(r'^orderinfo/$',CenterViews.myhome_orderinfo,name="myhome_orderinfo"),

    # 订单
    url(r'^order/confirm/',OrderViews.myhome_order_confirm,name="myhome_order_confirm"),
    url(r'^order/create/',OrderViews.myhome_order_create,name="myhome_order_create"),
    url(r'^order/pay/',OrderViews.myhome_order_pay,name="myhome_order_pay"),
    url(r'^order/pay/success/',OrderViews.myhome_order_paysuccess,name="myhome_order_paysuccess"),

    # 支付回调地址
    url(r'^order/pay_result/$',OrderViews.myhome_pay_result,name="myhome_pay_result"),
]

web/web/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ueditor/', include('ueditor.urls')),
    url(r'^myadmin/', include('myadmin.urls')),
    url(r'^',include('myhome.urls')),
]

web/myadmin/models.py
from django.db import models

# Create your models here.


# 定义会员模型
class Users(models.Model):
    nikename = models.CharField(max_length=20,null=True)
    password = models.CharField(max_length=80)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=100)
    age = models.IntegerField(null=True,default=0)
    pic_url = models.CharField(max_length=100)
    SEX_CHOICES = {
        (0,'女'),
        (1,'男'),
    }
    sex = models.CharField(max_length=1,null=True,choices=SEX_CHOICES)
    # 0 正常 1 禁用 2 删除 ...
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)

    # 自定义 会员管理 权限
    class Meta:
        permissions=(
            ("show_Uswrs","查看用户列表权限"),
            ("create_Users","添加用户信息权限"),
            ("edit_Users","修改用户信息权限"),
            ("remove_Users","删除用户信息权限")
        )

# 商品分类模型
class Cates(models.Model):
    name = models.CharField(max_length=20)
    pid = models.IntegerField()
    path = models.CharField(max_length=50)
    # 自定义 商品分类管理 权限
    class Meta:
        permissions = (
            ("show_Cates", "查看分类列表权限"),
            ("create_Cates", "添加分类信息权限"),
            ("edit_Cates", "修改分类信息权限"),
            ("remove_Cates", "删除分类信息权限"),
        )

# 商品模型
class Goods(models.Model):
    # id 所属分类，商品名，图片，添加时间，销量

    cateid = models.ForeignKey(to="Cates",to_field="id",on_delete=models.CASCADE)
    goodsname = models.CharField(max_length=50)
    title = models.CharField(max_length=255)
    brand = models.CharField(max_length=50)
    color = models.CharField(max_length=50,default="")
    sizes = models.CharField(max_length=50,default="")
    price = models.FloatField()
    goodsnum = models.IntegerField()
    pic_url = models.CharField(max_length=255)
    goodsinfo = models.TextField(null=True)
    ordernum = models.IntegerField(default=0)
    clicknum = models.IntegerField(default=0)
    #0新品 1热卖 2推荐 3下架
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)
    # 自定义 商品管理 权限
    class Meta:
        permissions = (
            ("show_Goods", "查看商品列表权限"),
            ("create_Goods", "添加商品信息权限"),
            ("edit_Goods", "修改商品信息权限"),
            ("remove_Goods", "删除商品信息权限"),
        )
   
# 购物车 模型
class Cart(models.Model):
    #  id 用户 uid 商品 goodsid 数量 num
    uid = models.ForeignKey(to="Users",to_field="id",on_delete=models.CASCADE)
    color = models.CharField(max_length=20,default="")
    sizes = models.CharField(max_length=20,default="")
    goodsid = models.ForeignKey(to="Goods",to_field="id",on_delete=models.CASCADE)
    num = models.IntegerField()
    lengths = models.IntegerField(default=1)

# 订单
    # id订单号 uid用户 收货人,收货地址,收货电话,总价,状态 支付方式 ,下单时间,支付时间
class Order(models.Model):
    uid = models.ForeignKey(to="Users",to_field="id",on_delete=models.CASCADE)
    username = models.CharField(max_length=20)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=255)
    totalprice = models.FloatField()
    # 0:未支付  1：已支付   2：已发货   3：已收货   4：已评价   5：取消
    status = models.IntegerField(default=0)
    # 0:支付宝  1：微信   2：银联   3：其他
    paytype = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)
    paytime = models.DateTimeField(null=True)

# 订单详情 
    # orderid   goodsid     num     price购买单价
class OrderInfo(models.Model):   
    orderid = models.ForeignKey(to="Order",to_field="id",on_delete=models.CASCADE)
    goodsid = models.ForeignKey(to="Goods",to_field="id",on_delete=models.CASCADE)
    num = models.IntegerField()
    price = models.FloatField()

    # 自定义 订单 权限
    class Meta:
        permissions = (
            ("show_Order", "查看订单列表权限"),
            ("create_Order", "添加订单信息权限"),
            ("edit_Order", "修改订单信息权限"),
            ("remove_Order", "删除订单信息权限"),
        )

web/myhome/models.py
from django.db import models
# from myadmin.models import Cates,Goods,Cart,Users
from myadmin.models import Users


# 地址管理模型
class Address(models.Model):
    uid = models.IntegerField()
    name = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=11)
    status = models.IntegerField()

# 个人中心收藏模型
class Collect(models.Model):
    uid = models.IntegerField()
    sid = models.IntegerField()
# Create your models here.

# 第三方登录用户信息模型
class OAuth_ex(models.Model):
    type = models.IntegerField(default=1)  # 1状态为github登录
    user = models.ForeignKey(Users,on_delete=models.CASCADE)
    openid = models.CharField(max_length=100, default='')

web/myadmin/views/UsersViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
import os
from django.contrib.auth.hashers import make_password, check_password
# 导入分页类
from django.core.paginator import Paginator
from ..models import Users
from web.settings import BASE_DIR
from django.contrib.auth.decorators import permission_required



# Create your views here.
# 用户模型的管理
# 会员添加表单
@permission_required('myadmin.create_User',raise_exception=True)
def user_add(request):

    return render(request,'myadmin/users/add.html')

# 会员执行添加
@permission_required('myadmin.create_User',raise_exception=True)
def user_insert(request):
    # 接收表单数据
    data=request.POST.dict()
    data.pop('csrfmiddlewaretoken')

    # 处理密码 加密
    data['password'] = make_password(data['password'],None, 'pbkdf2_sha256')

    # 头像上传
    # 接收上传的文件
    myfile = request.FILES.get('pic',None)
    if not myfile:
        # 没有上传头像
        return HttpResponse('<script>alert("没有选择头像上传");history.back(-1);</script>')
    # 处理头像上传  1.jpg ==> [1,jpg]
    data['pic_url']=uploads_pic(myfile)

    try:
        # 创建模型，添加数据
        ob = Users(**data)
        ob.save()
        return HttpResponse('<script>alert("添加成功");location.href="/myadmin/user/index";</script>')
    except:
        pass
    return HttpResponse('<script>alert("添加失败");history.back(-1);</script>')

    
# 会员列表
@permission_required('myadmin.show_User',raise_exception=True)
def user_index(request):
    # 获取所有用户的数据
    data = Users.objects.all()

    # 获取搜索条件
    types = request.GET.get('types',None)
    keywords = request.GET.get('keywords',None)
    # 判断是否搜索
    if types:
        from django.db.models import Q
        data = data.filter(Q(id__contains=keywords)|Q(nikename__contains=keywords)|Q(phone__contains=keywords)|Q(email__contains=keywords))
    elif types:
        search = {types+'__contains':keywords}
        data = data.filter(**search)
    
    print(data)
    # 实例化分页类
    p = Paginator(data,10) 

    # 获取当前的页码数
    pageindex=request.GET.get('page',1)

    # 获取当前页的数据
    userlist=p.page(pageindex)

    # 分配数据
    context={'userlist':userlist}

    # 加载模板
    return render(request,'myadmin/users/index.html',context)

# 会员编辑
@permission_required('myadmin.edit_User',raise_exception=True)
def user_edit(request):
    # 接收用户ID
    uid = request.GET.get('uid')
    # 获取当前会员对象
    ob = Users.objects.get( id=uid)

    # 判断当前的请求方式
    if request.method=='POST':
        # 执行更新
        # 判断密码是否更新
        password_now=request.POST.get('password',None)
        if password_now:
            # 更新密码
            ob.password=make_password(request.POST['password'],None,'pbkdf2_sha256')
        
        myfile = request.FILES.get('pic',None)
        myfile_now = request.POST.get('pic_url',None)

        # 判断数据库中的pic_url是否为空
        if myfile_now:
            if myfile:
                # 如有新头像上传，则先删除原头像
                os.remove(BASE_DIR+ob.pic_url)
                ob.pic_url=uploads_pic(myfile)
        else:
            ob.pic_url=uploads_pic(myfile)


        # 更新其他字段
        ob.nikename = request.POST.get('nikename')
        ob.email = request.POST.get('email')
        ob.phone = request.POST.get('phone')
        ob.age = request.POST.get('age')
        ob.sex = request.POST.get('sex')
        ob.save()
        return HttpResponse('<script>alert("更新成功");location.href="/myadmin/user/index/";</script>')
    else:

        # 显示编辑表单
        context={'uinfo':ob}
        # 加载模板
        return render(request,'myadmin/users/edit.html',context)

# 会员状态更新
def user_set_status(request):
    # 通过uid获取当前会员对象
    ob=Users.objects.get(id=request.GET.get('uid'))
    ob.status = request.GET.get('status')
    ob.save()
    return JsonResponse({'msg':'状态更新成功','code':0})


# 处理头像上传代码 
def uploads_pic(myfile):
    try:
        import time
        filename = str(time.time())+"."+myfile.name.split('.').pop()
        destination = open(BASE_DIR+"/static/uploads/userpic/"+filename,"wb+")
        for chunk in myfile.chunks():      # 分块写入文件  
            destination.write(chunk)  
        destination.close()
        return '/static/uploads/userpic/'+filename
    except:
        return False

web/myhome/views/CartViews.py
from django.shortcuts import render
from django.http import HttpResponse, Http404,JsonResponse
from myadmin.models import Users,Cates,Goods,Cart

# 购物车列表
def myhome_cart_index(request):
    # 获取当前用户的购物车数据
    VipUser = request.session.get('VipUser')
    # 判断是否登录
    if VipUser:
        data = Cart.objects.filter(uid=VipUser['uid'])
        context = {'cartdata':data}
        return render(request,'myhome/cart/index.html',context)
    else:
        return HttpResponse('<script>alert("您还未登陆，请先登录!");history.back()</script>')

def myhome_cart_add(request):
    
    try:
        # 执行购物车的商品添加
        data = request.GET.dict()
        data['goodsid'] = Goods.objects.get(id=data['goodsid'])
        data['uid'] = Users.objects.get(id=request.session.get('VipUser')['uid'])
        # 先检测当前的商品是否已经在当前用户的购物车中
        ob = Cart.objects.filter(uid=data['uid']).filter(goodsid=data['goodsid'])

        if ob.count():
            # 0：尺码和颜色都只有一个选项，1:尺码有2个选项以上，2：颜色有2个选项以上，3：尺码和颜色都有2个选项以上
            # 存在 获取当前购物车对象
            cart = Cart.objects.get(id=ob[0].id)
            num=int(data['num'])
            cart.num += num
            lengths=int(data['lengths'])
            if lengths==3:
                cart.sizes+=((','+data['sizes'])*num)
                cart.color+=((','+data['color'])*num)
                cart.save()
            elif lengths==2:
                cart.sizes=data['sizes']
                cart.color+=((','+data['color'])*num)
                cart.save()
            elif lengths==1:
                cart.sizes+=((','+data['sizes'])*num)
                cart.color=data['color']
                cart.save()
            else:
                cart.sizes=data['sizes']
                cart.color=data['color']
                cart.save()

        else:
            # 不存在
            # 存入 cart模型中
            ob = Cart(**data)
            num=int(data['num'])
            ob.num = num
            lengths=int(data['lengths'])

            ob.sizes=data['sizes']
            ob.color=data['color']
            ob.save()

        return JsonResponse({'code':0,'msg':'加入购物车成功!'})
    except:
        pass

    return JsonResponse({'code':1,'msg':'加入购物车失败!'})

# 商品删除
def myhome_cart_del(request):
    try:
        # cartid
        cartid = request.GET.get('cartid')
        # 获取当前购物车商品对象
        ob = Cart.objects.get(id=cartid)
        # 执行删除
        ob.delete()
        return JsonResponse({'code':0,'msg':'删除成功'})
    except:
        pass

    return JsonResponse({'code':1,'msg':'删除失败'})

# 购物车商品数量修改
def myhome_cart_edit(request):
    try:
        cartid = request.GET.get('cartid')
        num = request.GET.get('num')
        ob = Cart.objects.get(id=cartid)
        ob.num=num
        ob.save()

        return JsonResponse({'code':0,'msg':'删除成功'})
    except:
        pass

    return JsonResponse({'code':1,'msg':'删除失败'})

# 购物车空页
def myhome_cart_empty(request):
    

    return render(request,'myhome/cart/empty.html')

# 商品清空
def myhome_cart_clear(request):
    

    return HttpResponse('myhome_cart_clear')

web/myhome/views/CenterViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from django.urls import reverse
from myadmin.models import Cates,Goods,Cart,Users,Order,OrderInfo
from myhome.models import Address


# 订单管理页面
def myhome_orderinfo(request):
    # 获取数据
    ob = Order.objects.filter(uid=request.session.get('VipUser')['uid'])

    context = {'orderdata':ob}
    
    return render(request,'myhome/Users/orderinfo.html',context)

web/templates/myhome/Users/orderinfo.html
{% extends 'myhome/index.html' %}

{% block title %}
<title>订单管理</title>
{% endblock %}

{% block css %}
<link href="/static/myhome/theme/css/systyle.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="/static/myhome/theme/css/member.css">
<link rel="stylesheet" type="text/css" href="/static/myhome/theme/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/myhome/theme/css/login.css">
<link rel="stylesheet" type="text/css" href="/static/myhome/theme/css/infstyle.css">
{% endblock %}

{% block header%}

{% endblock %}

{% block der %}

{% endblock%}

{% block banner %}

{% endblock %}

{% block con %}
<section id="member">
  <div class="member-center clearfix">
    <div class="member-left fl">
      <div class="ddzx"><a href="{% url 'myhome_personal' %}">个人中心</a></div>
      <div class="subddzx">
        <ul>
          <li><a href="{% url 'myhome_information' %}">个人信息</a></li>
          <li><a href="{% url 'myhome_safety' %}">安全设置</a></li>
          <li><a href="{% url 'myhome_address' %}">地址管理</a></li>
          <li><a href="{% url 'myhome_collect' %}">我的收藏</a></li>
        </ul>
      </div>
      <div class="ddzx"><a href="">我的交易</a></div>
      <div class="subddzx">
        <ul>
          <li><a href="{% url 'myhome_orderinfo' %}">订单管理</a></li>
          <li><a href="">退款售后</a></li>
          <li><a href="">评价商品</a></li>
        </ul>
      </div>
    </div>
    <div class="member-right fr">
      <div class="member-head">
        <div class="member-heels fl">
          <strong class="am-text-danger am-text-lg" style="color:#fff;">订单管理</strong>
        </div>
      </div>
      <div class="member-switch clearfix">
        <ul id="H-table" class="H-table">
          <li class="cur"><a href="#">我的订单 <em></em></a></li>
          <li><a href="#">退货/退款记录 <em></em></a></li>
        </ul>
      </div>
      <div class="member-border">
        <div class="member-return H-over">
          <div class="member-cancel clearfix">
            <span class="be1">订单信息</span>
            <span class="be2">收货人</span>
            <span class="be2">订单金额</span>
            <span class="be2">订单时间</span>
            <span class="be2">订单状态</span>
            <span class="be2">订单操作</span>
          </div>
          <div class="member-sheet clearfix">
            <ul>
              {% for v in orderdata %}
              <li>
                <div class="member-circle clearfix">
                  <div class="ci1">
                    {% for vv in v.orderinfo_set.all %}
                    <div class="ci7 clearfix">
                      <span class="gr1"><a href="#"><img src="{{ vv.goodsid.pic_url}}" width="60" height="60" title=""
                            about=""></a></span>
                      <span class="gr2"><a href="{% url 'myhome_info' %}?goodsid={{ vv.goodsid.id }}">{{ vv.goodsid.goodsname }}</a></span>
                      <span class="gr3">X<i>{{ vv.num }}</i></span>
                    </div>
                    {% endfor %}
                  </div>
                  <div class="ci2">{{ v.username }}</div>
                  <div class="ci3"><b style="color: #E02B41;">￥{{ v.totalprice }}</b>
                    {% if v.paytype == 0 %}
                      <p>支付宝</p>
                    {% elif v.status == 1 %}
                      <p>微信 支付</p>
                    {% endif %}

                    <p class="iphone">手机订单</p>
                  </div>
                  <div class="ci4">
                    <p>{{ v.addtime }}</p>
                  </div>
                  <div class="ci5">
                    {% if v.status == 0%}
                      <div>未支付<br></div>
                    {% elif v.status == 1%}
                      <div>已支付<br></div>
                    {% endif %}
                    <p><a href="#">订单详情</a></p>
                  </div>
                  <div class="ci6">
                    <p><a href="#">申请退货</a> </p>
                  </div>
                </div>
                
                <div class="member-minute clearfix" style="border-top:1px solid #ccc;">
                  <span>下单时间：<em>{{ v.addtime|date:'Y-m-d H:i:s' }}</em></span>
                  <span>订单号：<em>{{ v.id }}</em></span>
                  <span class="member-custom">客服电话：<em>010-6544-0986</em></span>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <!-- <div class="member-return H-over" style="display:none;">
          <div class="member-cancel clearfix">
            <span class="be1">订单信息</span>
            <span class="be2">收货人</span>
            <span class="be2">订单金额</span>
            <span class="be2">订单时间</span>
            <span class="be2">订单状态</span>
            <span class="be2">订单操作</span>
          </div>
          <div class="member-sheet clearfix">
            <ul>
              <li>
                <div class="member-minute clearfix">
                  <span>2015-09-22 18:22:33</span>
                  <span>订单号：<em>98653056821</em></span>
                  <span><a href="#">以纯甲醇旗舰店</a></span>
                  <span class="member-custom">客服电话：<em>010-6544-0986</em></span>
                </div>
                <div class="member-circle clearfix">
                  <div class="ci1">
                    <div class="ci7 clearfix">
                      <span class="gr1"><a href="#"><img src="../theme/img/pd/m1.png" width="60" height="60" title=""
                            about=""></a></span>
                      <span class="gr2"><a href="#">红米Note2 标准版 白色 移动4G手机 双卡双待</a></span>
                      <span class="gr3">X1</span>
                    </div>
                    <div class="ci7 clearfix">
                      <span class="gr1"><a href="#"><img src="../theme/img/pd/m2.png" width="60" height="60" title=""
                            about=""></a></span>
                      <span class="gr2"><a href="#">AXON天机mini NBA限量版</a></span>
                      <span class="gr3">X9</span>
                    </div>
                  </div>
                  <div class="ci2">张子琪</div>
                  <div class="ci3"><b>￥120.00</b>
                    <p>货到付款</p>
                    <p class="iphone">手机订单</p>
                  </div>
                  <div class="ci4">
                    <p>2015-09-22</p>
                  </div>
                  <div class="ci5">
                    <p>已申请退货</p>
                    <p><a href="#">退货日志</a></p>
                  </div>
                  <div class="ci6">
                    <p><a href="#">取消退货</a> </p>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div> -->

        <div class="clearfix" style="padding:30px 20px;">
          <div class="fr pc-search-g pc-search-gs">
            <a style="display:none" class="fl " href="#">上一页</a>
            <a href="#" class="current">1</a>
            <a href="javascript:;">2</a>
            <a href="javascript:;">3</a>
            <a href="javascript:;">4</a>
            <a href="javascript:;">5</a>
            <a href="javascript:;">6</a>
            <a href="javascript:;">7</a>
            <span class="pc-search-di">…</span>
            <a href="javascript:;">1088</a>
            <a title="使用方向键右键也可翻到下一页哦！" class="" href="javascript:;">下一页</a>
          </div>
        </div>

      </div>
    </div>


  </div>
</section>

<script type="text/javascript">
  (function (a) {
    a.fn.hoverClass = function (b) {
      var a = this;
      a.each(function (c) {
        a.eq(c).hover(function () {
          $(this).addClass(b)
        }, function () {
          $(this).removeClass(b)
        })
      });
      return a
    };
  })(jQuery);

  $(function () {
    $("#pc-nav").hoverClass("current");
  });

  $(function () {

    $("#H-table li").each(function (i) {
      $(this).click((function (k) {
        var _index = k;
        return function () {
          $(this).addClass("cur").siblings().removeClass("cur");
          $(".H-over").hide();
          $(".H-over:eq(" + _index + ")").show();
        }
      })(i));
    });
    $("#H-table1 li").each(function (i) {
      $(this).click((function (k) {
        var _index = k;
        return function () {
          $(this).addClass("cur").siblings().removeClass("cur");
          $(".H-over1").hide();
          $(".H-over1:eq(" + _index + ")").show();
        }
      })(i));
    });
  });
</script>
{% endblock %}

{% block jsbanner %}
{% endblock %}