web/myadmin/urls.py
from django.conf.urls import url
from . views import IndexViews,UsersViews,CatesViews,GoodsViews,CenterViews

urlpatterns = [
    url(r'^index/$',IndexViews.index,name="myadmin_index"),

    # 权限管理
    # 管理员管理
    url(r'^auth/user/index/$',IndexViews.myadmin_authuser_index,name="myadmin_authuser_index"),
    url(r'^auth/user/add/$',IndexViews.myadmin_authuser_add,name="myadmin_authuser_add"),
    url(r'^auth/user/insert/$',IndexViews.myadmin_authuser_insert,name="myadmin_authuser_insert"),
    url(r'^auth/user/edit/$',IndexViews.myadmin_authuser_edit,name="myadmin_authuser_edit"),

    # 权限管理组
    url(r'^auth/group/index/$',IndexViews.myadmin_authgroup_index,name="myadmin_authgroup_index"),
    url(r'^auth/group/add/$',IndexViews.myadmin_authgroup_add,name="myadmin_authgroup_add"),
    url(r'^auth/group/insert/$',IndexViews.myadmin_authgroup_insert,name="myadmin_authgroup_insert"),
    url(r'^auth/group/edit/$',IndexViews.myadmin_authgroup_edit,name="myadmin_authgroup_edit"),
 

    # 登录页
    url(r'^login/$',IndexViews.myadmin_login,name="myadmin_login"),
    url(r'^dologin/$',IndexViews.myadmin_dologin,name="myadmin_dologin"),
    url(r'^logout/$',IndexViews.myadmin_logout,name="myadmin_logout"),
    url(r'^verifycode/$',IndexViews.verifycode,name="myadmin_vcode"),

    # 会员管理
    url(r'^user/add/$', UsersViews.user_add,name="myadmin_user_add"),
    url(r'^user/insert/$', UsersViews.user_insert,name="myadmin_user_insert"),
    url(r'^user/index/$', UsersViews.user_index,name="myadmin_user_index"),
    url(r'^user/edit/$',UsersViews.user_edit,name="myadmin_user_edit"),
    url(r'^user/setstutus/$', UsersViews.user_set_status,name="myadmin_user_set_status"),

    # 分类管理
    url(r'^cate/add/$',CatesViews.cate_add,name="myadmin_cate_add"),
    url(r'^cate/index/$',CatesViews.cate_list,name="myadmin_cate_index"),
    url(r'^cate/del/$',CatesViews.cate_del,name="myadmin_cate_del"),
    url(r'^cate/edit/$',CatesViews.cate_edit,name="myadmin_cate_edit"),

    # 商品管理
    url(r'^goods/add/$',GoodsViews.goods_add,name="myadmin_goods_add"),
    url(r'^goods/index/$', GoodsViews.goods_index,name="myadmin_goods_index"),
    url(r'^goods/insert/$',GoodsViews.goods_insert,name="myadmin_goods_insert"),
    url(r'^goods/edit/$',GoodsViews.goods_edit,name="myadmin_goods_edit"),
    url(r'^goods/del/$',GoodsViews.goods_del,name="myadmin_goods_del"),

    # 订单管理
    url(r'^center/index/$',CenterViews.center_index,name="myadmin_center_index"),
    url(r'^center/erit/$',CenterViews.center_edit,name="myadmin_center_edit"),

    
  

    
]   

web/web/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ueditor/', include('ueditor.urls')),
    url(r'^myadmin/', include('myadmin.urls')),
    url(r'^',include('myhome.urls')),
]

web/myadmin/models.py
from django.db import models

# Create your models here.


# 定义会员模型
class Users(models.Model):
    nikename = models.CharField(max_length=20,null=True)
    password = models.CharField(max_length=80)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=100)
    age = models.IntegerField(null=True,default=0)
    pic_url = models.CharField(max_length=100)
    SEX_CHOICES = {
        (0,'女'),
        (1,'男'),
    }
    sex = models.CharField(max_length=1,null=True,choices=SEX_CHOICES)
    # 0 正常 1 禁用 2 删除 ...
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)

    # 自定义 会员管理 权限
    class Meta:
        permissions=(
            ("show_Uswrs","查看用户列表权限"),
            ("create_Users","添加用户信息权限"),
            ("edit_Users","修改用户信息权限"),
            ("remove_Users","删除用户信息权限")
        )

# 商品分类模型
class Cates(models.Model):
    name = models.CharField(max_length=20)
    pid = models.IntegerField()
    path = models.CharField(max_length=50)
    # 自定义 商品分类管理 权限
    class Meta:
        permissions = (
            ("show_Cates", "查看分类列表权限"),
            ("create_Cates", "添加分类信息权限"),
            ("edit_Cates", "修改分类信息权限"),
            ("remove_Cates", "删除分类信息权限"),
        )

# 商品模型
class Goods(models.Model):
    # id 所属分类，商品名，图片，添加时间，销量

    cateid = models.ForeignKey(to="Cates",to_field="id",on_delete=models.CASCADE)
    goodsname = models.CharField(max_length=50)
    title = models.CharField(max_length=255)
    brand = models.CharField(max_length=50)
    color = models.CharField(max_length=50,default="")
    sizes = models.CharField(max_length=50,default="")
    price = models.FloatField()
    goodsnum = models.IntegerField()
    pic_url = models.CharField(max_length=255)
    goodsinfo = models.TextField(null=True)
    ordernum = models.IntegerField(default=0)
    clicknum = models.IntegerField(default=0)
    #0新品 1热卖 2推荐 3下架
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)
    # 自定义 商品管理 权限
    class Meta:
        permissions = (
            ("show_Goods", "查看商品列表权限"),
            ("create_Goods", "添加商品信息权限"),
            ("edit_Goods", "修改商品信息权限"),
            ("remove_Goods", "删除商品信息权限"),
        )
   
# 购物车 模型
class Cart(models.Model):
    #  id 用户 uid 商品 goodsid 数量 num
    uid = models.ForeignKey(to="Users",to_field="id",on_delete=models.CASCADE)
    color = models.CharField(max_length=20,default="")
    sizes = models.CharField(max_length=20,default="")
    goodsid = models.ForeignKey(to="Goods",to_field="id",on_delete=models.CASCADE)
    num = models.IntegerField()
    lengths = models.IntegerField(default=1)

# 订单
    # id订单号 uid用户 收货人,收货地址,收货电话,总价,状态 支付方式 ,下单时间,支付时间
class Order(models.Model):
    uid = models.ForeignKey(to="Users",to_field="id",on_delete=models.CASCADE)
    username = models.CharField(max_length=20)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=255)
    totalprice = models.FloatField()
    # 0:未支付  1：已支付   2：已发货   3：已收货   4：已评价   5：取消
    status = models.IntegerField(default=0)
    # 0:支付宝  1：微信   2：银联   3：其他
    paytype = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)
    paytime = models.DateTimeField(null=True)

# 订单详情 
    # orderid   goodsid     num     price购买单价
class OrderInfo(models.Model):   
    orderid = models.ForeignKey(to="Order",to_field="id",on_delete=models.CASCADE)
    goodsid = models.ForeignKey(to="Goods",to_field="id",on_delete=models.CASCADE)
    num = models.IntegerField()
    price = models.FloatField()

    # 自定义 订单 权限
    class Meta:
        permissions = (
            ("show_Order", "查看订单列表权限"),
            ("create_Order", "添加订单信息权限"),
            ("edit_Order", "修改订单信息权限"),
            ("remove_Order", "删除订单信息权限"),
        )

web/myadmin/views/CatesViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from .. models import Cates
from django.urls import reverse
# 导入分页类
from django.core.paginator import Paginator
from django.contrib.auth.decorators import permission_required

# Create your views here.


def get_cates_all(request):
    
    # select *,concat(path,id) as paths from myadmin_cates order by paths;
      # 获取所有分类
    data= Cates.objects.extra(select ={'paths':'concat(path,id)'}).order_by('paths')
     # 获取搜索条件
    types = request.GET.get('types',None)
    keywords = request.GET.get('keywords',None)
    # 判断是否搜索
    if types:
        from django.db.models import Q
        data = data.filter(Q(id__contains=keywords)|Q(name__contains=keywords))
    elif types:
        search = {types+'__contains':keywords}
        data = data.filter(**search)

    for x in data:
        l=x.path.count(',')-1
        
        x.sub=l*'>'
        if x.pid==0:
            x.pname='顶级分类'
        else:
            pob = Cates.objects.get(id=x.pid)
            x.pname = pob.name

    return data

# 分类列表
@permission_required('myadmin.show_Cates',raise_exception=True)
def cate_list(request):
    data=get_cates_all(request)
    # data = Cates.objects.all()

     # 实例化分页类
    p = Paginator(data,10) 
    print(data)
    # 获取当前的页码数
    pageindex=request.GET.get('page',1)

    # 获取当前页的数据
    catelist=p.page(pageindex)
    # 分配数据
    context = {'catelist':catelist}
    # 加载模板
    return render(request,'myadmin/cates/index.html',context)

# 分类添加
@permission_required('myadmin.create_Cates',raise_exception=True)
def cate_add(request):
    if request.method == 'POST':
        # 接收数据
        data={}
        data['name'] = request.POST.get('name')
        data['pid']=request.POST.get('pid')
        # data['path']='0,'

        # 判断path路径
        if data['pid'] == '0':
            data['path'] = '0,'
        else:
            # 获取当前父级的path路径
            pob = Cates.objects.get(id=data['pid'])
            # 拼接当前数据的path
            data['path'] = pob.path+data['pid']+','
        print(data,data['pid'])
        # 数据入库
        ob = Cates(**data)
        ob.save()

        return HttpResponse('<script>alert("添加成功");location.href="'+reverse('myadmin_cate_add')+'";</script>')
    else:
        # 获取当前已有的 分类
        catelist=get_cates_all(request)
        # # 分配数据
        context = {'catelist':catelist}
        # # 加载模板

        return render(request,'myadmin/cates/add.html',context)

# 分类删除
def cate_del(request):
    # 接收数据
    cid = request.GET.get('cid')

    # 判断当前分类下是否还有子类
    res = Cates.objects.filter(pid=cid).count()
    if res:
        # 有子类
        return JsonResponse({'msg':'当前类下有子类，不能删除','code':1})

    # 判断当前分类下是否还有商品发布


    # 执行删除
    ob = Cates.objects.get(id=cid)
    ob.delete()
    return JsonResponse({'msg':'删除成功','code':0})
    

# 分类名称修改
def cate_edit(request):
    try:
        # 获取 参数
        cid=request.GET.get('cid')
        newname=request.GET.get('newname')

        # 获取对象
        ob = Cates.objects.get(id=cid)
        ob.name=newname
        # 保存修改
        ob.save()
        data={'msg':'更新成功','code':0}
    except:
        data={'msg':'更新失败','code':1}

    return JsonResponse(data)

web/myadmin/views/CenterViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from .. models import Cates,Goods,Cart,Users,Order,OrderInfo
from django.urls import reverse
# 导入分页类
from django.core.paginator import Paginator
from django.contrib.auth.decorators import permission_required

# Create your views here.

# 订单管理列表
@permission_required('myadmin_show_Order',raise_exception=True)
def center_index(request):
    # 获取数据
    data = Order.objects.all()
    # 获取搜索条件
    types = request.GET.get('types',None)
    keywords = request.GET.get('keywords',None)
    # 判断是否搜索
    if types:
        from django.db.models import Q
        data = data.filter(Q(id__contains=keywords)|Q(username__contains=keywords)|Q(phone__contains=keywords)
        |Q(address__contains=keywords)|Q(addtime__contains=keywords))
    elif types:
        search = {types+'__contains':keywords}
        data = data.filter(**search)

    # 实例化分页类
    p = Paginator(data,10) 
    # 获取当前的页码数
    pageindex=request.GET.get('page',1)

    # 获取当前页的数据
    cardata=p.page(pageindex)

    context={'cardata':cardata}

    return render(request,'myadmin/center/index.html',context)

# 订单修改
@permission_required('myadmin_create_Order',raise_exception=True)
def center_edit(request):

    # 接收用户id
    uid = request.GET.get('uid')
    # 获取当前用户的对象
    ob = Order.objects.get(id=uid)

    # 判断当前的请求方式
    if request.method == 'POST':
        # 执行更新操作           
        # 更新其他字段
        ob.username = request.POST.get('username')
        ob.phone = request.POST.get('phone')
        ob.address = request.POST.get('address')
        ob.totalprice = request.POST.get('totalprice')
        ob.status = request.POST.get('status')
        ob.paytype = request.POST.get('paytype')
        ob.addtime = request.POST.get('addtime')
        ob.paytime = request.POST.get('paytime')
        ob.save()
        return HttpResponse('<script>alert("更新成功");location.href="/myadmin/center/index/";</script>')
    else:
         # 显示编辑表单
        context={'uinfo':ob}
        # 加载模板
        return render(request,'myadmin/center/edit.html',context)

web/myadmin/views/GoodsViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from django.core.paginator import Paginator
from web.settings import BASE_DIR
from .CatesViews import get_cates_all
from .. models import Cates, Goods
from django.contrib.auth.decorators import permission_required


# Create your views here.

@permission_required('myadmin_show_Goods',raise_exception=True)
def goods_index(request):
    # 获取当前所有的商品数据
    data=Goods.objects.all()

      # 获取搜索条件
    types = request.GET.get('types',None)
    keywords = request.GET.get('keywords',None)
    # 判断是否搜索
    if types:
        from django.db.models import Q
        data = data.filter(Q(id__contains=keywords)|Q(goodsname__contains=keywords)|Q(title__contains=keywords))
    elif types:
        search = {types+'__contains':keywords}
        data = data.filter(**search)
    
    
    # 实例化分页类
    p = Paginator(data,10) 
    # 获取当前的页码数
    pageindex=request.GET.get('page',1)

    # 获取当前页的数据
    goodslist=p.page(pageindex)

    # 分配数据
    context={'goodslist':goodslist}

    # 加载模板
    return render(request,'myadmin/goods/index.html',context)

@permission_required('myadmin_create_Goods',raise_exception=True)
def goods_insert(request):
    try:
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        # 处理 分类对象
        data['cateid'] = Cates.objects.get(id=data['cateid'])

        # 判断是否有图片上传
        myfile = request.FILES.get('pic', None)
        if not myfile:
            return HttpResponse('<script>alert("必须上传商品图片!");history.back(-1);</script>')
        data['pic_url'] = uploads_pic(myfile)

        # 执行添加
        ob = Goods(**data)
        ob.save()
        return HttpResponse('<script>alert("商品添加成功!");location.href="/myadmin/goods/index/";</script>')
    except:
        pass

    return HttpResponse('<script>alert("商品添加失败!");history.back(-1);</script>')

@permission_required('myadmin_create_Goods',raise_exception=True)
def goods_add(request):

     # 获取当前所有的分类数据
    data = get_cates_all(request)
    context = {'catelist': data}

    # 加载模板
    return render(request, 'myadmin/goods/add.html', context)

@permission_required('myadmin_create_Goods',raise_exception=True)
def goods_edit(request):
    # 接收用户id
    uid = request.GET.get('uid')
    # 获取当前用户的对象
    ob = Goods.objects.get(id=uid)

    # 判断当前的请求方式
    if request.method == 'POST':
        # 执行更新操作
        myfile = request.FILES.get('pic',None)
        myfile_now = request.POST.get('pic_url',None)

        # 判断数据库中的pic_url是否为空
        if myfile_now:
            if myfile:
                # 如有新头像上传，则先删除原头像
                os.remove(BASE_DIR+ob.pic_url)
                ob.pic_url=uploads_pic(myfile)
        else:
            ob.pic_url=uploads_pic(myfile)
            
        # 更新其他字段
        ob.goodsname = request.POST.get('goodsname')
        ob.title = request.POST.get('title')
        ob.price = request.POST.get('price')
        ob.brand = request.POST.get('brand')
        ob.color = request.POST.get('color')
        ob.sizes = request.POST.get('sizes')
        ob.goodsnum = request.POST.get('goodsnum')
        ob.goodsinfo = request.POST.get('goodsinfo')
        ob.save()
        return HttpResponse('<script>alert("更新成功");location.href="/myadmin/goods/index/";</script>')
    else:

        # 显示编辑表单
        context={'uinfo':ob}
        # 加载模板
        return render(request,'myadmin/goods/edit.html',context)

# 删除
@permission_required('myadmin_create_Goods',raise_exception=True)
def goods_del(request):
    # 接收数据
    cid = request.GET.get('cid')
    ordernum = request.GET.get('ordernum')

    # 获取当前用户的对象
    ob = Goods.objects.get(id=cid)
    if ob.ordernum>0:
        # 有订货
        return JsonResponse({'msg':'当前类下商品有订购，不能删除','code':1})

    # 判断当前分类下是否还有商品发布


    # 执行删除
    ob = Goods.objects.get(id=cid)
    ob.delete()
    return JsonResponse({'msg':'删除成功','code':0})

# 处理头像上传代码
def uploads_pic(myfile):
    try:
        import time
        filename = str(time.time())+"."+myfile.name.split('.').pop()
        destination = open(BASE_DIR+"/static/uploads/commodity/"+filename,"wb+")
        for chunk in myfile.chunks():      # 分块写入文件
            destination.write(chunk)
        destination.close()
        return '/static/uploads/commodity/'+filename
    except:
        return False

web/templates/myadmin/cates/add.html
{% extends 'myadmin/index.html' %}

{% block title %}
<title>后台分类添加</title>
{% endblock %}


{% block con %}
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>分类添加</h3>
        </div>
    </div>
</div>
<div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">


                <form class="form-horizontal form-label-left "
                    action="{% url 'myadmin_cate_add' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <span class="section">分类信息填写</span>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">商品所属分类 
                            <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select name="pid"  class="form-control" >
                                <option value="0">顶级分类</option>
                                {% for v in catelist %}
                                <option value="{{v.id}}">{{v.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">分类名称 <span
                                class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input name="name" class="form-control col-md-7 col-xs-12"
                                data-validate-length-range="6" data-validate-words="2" placeholder="分类名称"
                                required="required" type="text">
                        </div>
                    </div>

                    

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-3">
                            <button id="send" type="submit" class="btn  btn-primary">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}

web/templates/myadmin/cates/index.html
{% extends 'myadmin/index.html' %}
{% block title %}
<title>后台分类</title>
{% endblock %}

{% block con %}
<link rel="stylesheet" href="/static/myadmin/assets/css/fontcss.css">
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>商品分类 </h2>
                <br>
                <form>
                <ul class="nav navbar-right panel_toolbox">
                    <div class="btn-group  btn-group-sm">
                        <a href="{% url 'myadmin_cate_add' %}" class="btn btn-default">新增</a>
                        <a class="btn btn-default" >删除</a>
                    </div>
                </ul>
                <div class="nav navbar-right panel_toolbox">
                    <div class=" col-md-3 col-sm-12 col-xs-12 form-group form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" name="keywords" value="{{ request.GET.keywords }}" class="form-control" 
                            placeholder="搜索...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-9 col-xs-12 pull-right">
                        <select class="form-control" name="types" data-am-selected="{btnSize: 'sm'}" >
                            <option value="all" {% if request.GET.types == 'all' %} selected {% endif %}>全局搜索</option>
                            <option value="id" {% if request.GET.types == 'id' %} selected {% endif %}>ID</option>
                            <option value="name" {% if request.GET.types == 'name' %} selected {% endif %}>名字</option>
                        </select>
                    </div>  
                </div>
                </form>  
            </div>
            <span class="pull-left" style="color:#ccc;">双击分类名可进行修改</span>
            <div class="x_content">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>分类名</th>
                            <th>所属父级</th>
                            <th>该类下的商品数量</th>
                            <th>Path路径</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for v in catelist %}

                        <tr class="fontcss">
                            <td scope="row">{{ v.id }}</td>
                            <td class="cate_name">
                                {{v.sub}} <span cid="{{v.id}}">{{v.name}}</span>
                            </td>
                            <td>{{ v.pname }}</td>
                            <td>{{ v.goods_set.count|default:'无' }}</td>
                            <td>{{ v.path }}</td>
                            <td>
                                <div>
                                    <a class="removeCate btn btn-xs btn-danger" cid="{{ v.id }}" href="javascript:void(0)">
                                        <i class="fa fa-trash"></i> 删除
                                    </a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
                
                
                <div class="btn-group pull-right">
                    <!-- <button class="btn btn-info" type="button">1</button>
                    <button class="btn btn-info active" type="button">2</button> -->
                    <ul class="pagination">
                        {% load pagetag %}

                        {% ShowsPage catelist.paginator.num_pages request%}
                    </ul>
                </div>

                </div>
            </div>
        </div>
    </div>

<script>
   $('.cate_name').dblclick(function(){
        var span=$(this).find('span')
        // 获取当前分类名字
        var catename=$(this).find('span').text()
        // 创建一个input
        var inp=$('<input type="text" value="'+catename+'" style="color:black;"></input>')
        // 把分类名换成input
        $(this).find('span').html(inp)
        inp.select()

        // 获取当前选择元素的分类 id
        var cid=span.attr('cid')

        // 给input绑定丧失焦点时间，判断是否更新了name，发送ajax
        inp.blur(function(){
            var newname= $(this).val()
            if(newname== catename){
                span.html(catename)
            }else{
                // 需要发送ajax去更新
                $.get('{% url 'myadmin_cate_edit' %}',{'cid':cid,'newname':newname},function(data){
                    // 判断是否更新成功
                    if(data['code']==0){
                        span.html(newname)
                        alert(data['msg'])
                    }
                })
            }
        })

    })

    $('.removeCate').click(function(){
        //  获取当前的元素的值
        var cid= $(this).attr('cid');
        var a=$(this)
        // 发送ajax请求
        $.get('{%url 'myadmin_cate_del'%}',{'cid':cid},function(data){
            if(data['code'] == 0){
                //删除成功
               a.parents('tr').remove()
            }
            alert(data['msg'])
        },'json')
    })
</script>
{% endblock %}